### ISSUE TITLE
Does `coar-notify:reviews` model the review of an AS2 `object` or an artefact at a repository?

### ISSUE THREAD

**Issue by phochste** [antleaf/notify-implementation#10]
When reviewing [Scenario 1](https://notify.coar-repositories.org/scenarios/1/) I came across this JSON-LD fragment:

```
"object": {
    "coar-notify:reviews": {
      "object": {
        "id": "https://repository.org/preprint/201203/421/",
        "ietf:cite-as": "https://doi.org/10.5555/12345680"
      }
    },
    "id": "https://overlay-journal.org/reviews/000001/00001",
    "ietf:cite-as": "https://doi.org/10.3214/987654",
    "type": [
      "Document",
      "sorg:Review"
    ]
 }
```

There is a nested `object` pattern here. The object with id `https://overlay-journal.org/reviews/000001/00001` and
the nested object with id `https://repository.org/preprint/201203/421/` , with a `coar-notify:reviews` in the middle as a relation between the two.

**Problem**

[1] There is a hidden blank node introduced in the `coar-notify:reviews` :

- because`coar-notify:reviews`doesn't have an `id` property
- because `coar-notify:reviews` is interpreted as a IRI resource (via the context document)
- because `object` is still interpreted as an `as2:object` at this point

[2] The reviews relationship currently models:

<https://overlay-journal.org/reviews/000001/00001> _reviews_ **something** and  
**something**  has an AS2 object <https://repository.org/preprint/201203/421/>

Wouldn't it be better to model:

<https://overlay-journal.org/reviews/000001/00001>   _reviews_   <https://repository.org/preprint/201203/421/>

This could be expressed in JSON-LD like (there are other serializations possible..):

```
"object": {
    "coar-notify:reviews": {
        "id": "https://repository.org/preprint/201203/421/",
        "ietf:cite-as": "https://doi.org/10.5555/12345680"
    },
    "id": "https://overlay-journal.org/reviews/000001/00001",
    "ietf:cite-as": "https://doi.org/10.3214/987654",
    "type": [
      "Document",
      "sorg:Review"
    ]
 }

**Comment by paulwalk** [comment]
I am inclined to agree with your suggested change. This will affect many of the scenarios as currently documented, so I will ask on the Slack channel if any of the implementors have a problem with this change.

**Comment by phochste** [comment]
There is another way to do the change, and that is adding in the context document this:

```
    "coar-notify:reviews": {
      "@type": "@id" ,
      "@container": "@index"
    },
```

With this trick, nothing needs to be changed in the existing examples. The nested `object` in `object/coar-notify:reviews/object` is ignored and all the properties of it are inherited to the `object/coar-notify:reviews`.

But, this has a disadvantage that a round tripping of JSON-LD -> triples -> JSON-LD would lead to a different
JSON-LD document (still with the same meaning for linked data aware applications). 

### Demo of this trick @container trick

A JSON-LD document that contains:

```
"object": {
    "coar-notify:reviews": {
      "object": {
        "id": "https://repository.org/preprint/201203/421/",
        "ietf:cite-as": "https://doi.org/10.5555/12345680"
      },
    }
    "id": "https://overlay-journal.org/reviews/000001/00001"
 }
```

would lead to triples where the nested `object` is ignored (which is what we want):

```
<https://overlay-journal.org/reviews/000001/00001> <http://purl.org/coar/notify_vocabulary/reviews> <https://repository.org/preprint/201203/421/> .
<https://repository.org/preprint/201203/421/> <http://www.iana.org/assignments/relation/cite-as> <https://doi.org/10.5555/12345680> .
```

but when you turn these triples back into JSON-LD you would get:

```
"object": {
    "coar-notify:reviews": {
        "id": "https://repository.org/preprint/201203/421/",
        "ietf:cite-as": "https://doi.org/10.5555/12345680"
    }
    "id": "https://overlay-journal.org/reviews/000001/00001"
 }
```
   
It would be better not to have this nested object all along (a suggested in my ticket), it will give a stability of
serialization for JSON and Linked data aware tools.

**Comment by paulwalk** [comment]
The docs have been updated to reflect the change suggested above - closing this issue
