### ISSUE TITLE
Use https in JSON-LD context document examples?

### ISSUE THREAD

**Issue by phochste** [antleaf/notify-implementation#14]
Currently the JSON-LD document point in the context to an HTTP address `http://purl.org/coar/notify` . Should be write here an HTTPS `https://purl.org/coar/notify` address?

Reason: these context urls are followed by JSONLD processors. On the web it is regard as unsafe to follow HTTP links from HTTPS hosted documents , and this might be unsupported in the future.

In case we want JSON-LD processors in web browsers access these documents it is better to use https in the examples. This doesn't change the document model.

**Comment by paulwalk** [comment]
Have fixed this.
