### ISSUE TITLE
Add CORS HTTP headers when serving the Notify JSON-LD context document

### ISSUE THREAD

**Issue by phochste** [antleaf/notify-implementation#18]
I've noticed that [JSON-LD playground](https://json-ld.org/playground/) is complaining about the missing CORS related HTTP headers for the Notify context documents. Without propper CORS Javascript clients in browser environments are prevented to access cross site documents (such as context documents). 

In a decentralised environment this CORS handling would support browser clients to handle notifications.

My suggestion is to try to add a [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) HTTP header to any served JSON-LD context document:

```
Access-Control-Allow-Origin: *
```

If this works, it can be added as technical guideline for implementers that want to publish their own context documents.

**Comment by phochste** [comment]
Yes it [works](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%2C%22https%3A%2F%2Fpurl.org%2Fcoar%2Fnotify%22%5D%2C%22actor%22%3A%7B%22id%22%3A%22https%3A%2F%2Forcid.org%2F0000-0002-1825-0097%22%2C%22name%22%3A%22Josiah%20Carberry%22%2C%22type%22%3A%22Person%22%7D%2C%22id%22%3A%22urn%3Auuid%3A0370c0fb-bb78-4a9b-87f5-bed307a509dd%22%2C%22object%22%3A%7B%22id%22%3A%22https%3A%2F%2Fsome-organisation.org%2Fresource%2F0021%22%2C%22ietf%3Acite-as%22%3A%22https%3A%2F%2Fdoi.org%2F10.4598%2F12123487%22%2C%22type%22%3A%22Document%22%7D%2C%22origin%22%3A%7B%22id%22%3A%22https%3A%2F%2Fsome-organisation.org%2Fsystem%22%2C%22inbox%22%3A%22https%3A%2F%2Fsome-organisation.org%2Fsystem%2Finbox%2F%22%2C%22type%22%3A%22Service%22%7D%2C%22target%22%3A%7B%22id%22%3A%22https%3A%2F%2Fgeneric-service.com%2Fsystem%22%2C%22inbox%22%3A%22https%3A%2F%2Fgeneric-service.com%2Fsystem%2Finbox%2F%22%2C%22type%22%3A%22Service%22%7D%2C%22type%22%3A%22Offer%22%7D)!

**Comment by paulwalk** [comment]
cool - closing this issue.
