### ISSUE TITLE
The 'type' property is variously represented as a string or as an array of string

### ISSUE THREAD

**Issue by paulwalk** [antleaf/notify-implementation#4]
The `type` property is variously represented as a string and an array of strings, in different properties. For example in the 'offer' pattern we have:

```json
"object": {
    "id": "https://origin-system.org/resources/0021",
    "ietf:cite-as": "https://doi.org/10.4598/12123487",
    "type": [
      "Document"
    ]
  },
```

while in an example of an object representing a repository resource we have:

```json
"object": {
    "id": "https://repository.org/preprint/201203/421/",
    "ietf:cite-as": "https://doi.org/10.5555/12345680",
    "type": "sorg:AboutPage",
    "url": {
      "id": "https://repository.org/preprint/201203/421/content.pdf",
      "media-type": "application/pdf",
      "type": [
        "Article",
        "sorg:ScholarlyArticle"
      ]
    }
  },
```

Is it better to standardise on using arrays of strings for all of these examples, even where the array may typically contain only one string? I would think this would make it easier for software implementation (especially when statically typed)?

**Comment by phochste** [comment]
In JSON-LD both are allowed:

```
type : "Document"
```

and 

```
type:  [ "Document" ]
```

have semantically the same meaning (because of the LD part in the JSON-LD). In general when parties want to implement JSON-LD they can expect all these cases. When the examples don't show this, at least it should be mentioned in an implementation note that both options will exist.

Related to this is also the compact version of JSON-LD (there is more than one serialisation of JSON-LD that expresses the same thing).

**Comment by paulwalk** [comment]
Understood. This means that consumers will need to actually treat the payloads as RDF (JSON-LD). If I were implementing this in software, for many use-cases I would be interested in being able to use standard JSON libraries to parse the payload if I could. This is why I was interested in considering how we might add constraints, to make the simple case easier for developers.

But I guess that's just not viable...

**Comment by phochste** [comment]
JSON is viable, but with some added logic. The ActivityPub community does have guidelines I think to keep the spec as close as possible to pure JSON as possible. 

I think, in COAR the `type: Document` would be too generic anyway and in reality this will always be an array of strings? COAR could have a SHOULD guideline that `type` is an array, but it can't be a MUST.

**Comment by paulwalk** [comment]
That all sounds fine. I will update the docs.

**Comment by paulwalk** [comment]
[Docs updated](https://notify.coar-repositories.org/changelog/) to reflect this discussion. All examples in the docs now use arrays for the `type` property, and the documentation states that an array SHOULD be used for this property.
