### ISSUE TITLE
Does the AS2 context contain an extra '#' ? 

### ISSUE THREAD

**Issue by phochste** [antleaf/notify-implementation#5]
In the examples I see :

```(JSON)
"@context": [
    "https://www.w3.org/ns/activitystreams#",
```

shouldn't that be:

```(JSON)
"@context": [
    "https://www.w3.org/ns/activitystreams",
```

**Comment by phochste** [comment]
The AS2 context resource URL (the URL where context schemas can be found) , `https://www.w3.org/ns/activitystreams` is not the same as the AS2 namespace url (which should contain a `#` `https://www.w3.org/ns/activitystreams#`). It is a bit confusing.

**Comment by paulwalk** [comment]
Thanks @phochste . I find this quite confusing, but I'm sure you are right, and I will update the documentation accordingly now.

But I would like to understand the distinction. If a JSON-LD document has a context containing a property like this:

`"as2:https://www.w3.org/ns/activitystreams"`

Then how is the namespace URI - `https://www.w3.org/ns/activitystreams#` ever derived from this?

**Comment by phochste** [comment]
The `@context : https://www.w3.org/ns/activitystreams` specifies the location of a json-ld resource which contains namespace declarations (and/or links to other resources). 

In the `https://www.w3.org/ns/activitystreams` there is a namespace defined `as2:https://www.w3.org/ns/activitystreams#`.

On can see by requesting via content negotiation the `https://www.w3.org/ns/activitystreams` in JSON-LD format:

```
curl -H 'Accept: application/ld+json' https://www.w3.org/ns/activitystreams
```

Or follow this link : https://www.w3.org/ns/activitystreams.jsonld

**Comment by paulwalk** [comment]
Thanks for the clear explanation @phochste! Closing this issue now.
