### ISSUE TITLE
Origin, target require a AS2 System type , could I be that AS2 Service type is meant?

### ISSUE THREAD

**Issue by phochste** [antleaf/notify-implementation#7]
The COAR notifications require for the `origin` and `target` an `as:System` type. But, this property doesn't exist in the https://www.w3.org/ns/activitystreams terms. Could it be that we need the AS2 `Service` type instead?

**Comment by paulwalk** [comment]
Thanks - yes - that is a mistake. I have corrected this in the documentation now. Closing this issue.
